CREATE TABLE IF NOT EXISTS ads_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    adset_id TEXT,
    adset_name TEXT,
    date_start TEXT,
    date_stop TEXT,
    impressions INTEGER,
    reach INTEGER,
    spend REAL,
    action_type TEXT,
    value INTEGER,
    clicks INTEGER,
    engagements INTEGER,
    leads INTEGER,
    messaging_conversation_started INTEGER,
    custom_conversion INTEGER,
    CTR REAL,
    CPL REAL,
    ROI REAL,
    CPC REAL,
    CPA REAL,
    CR REAL,
    cost_per_messaging_conversation_started REAL,
    cost_per_custom_conversion REAL
);